name: Generate Snake

on:
  schedule:
    - cron: '0 0 * * *' # Runs at midnight UTC daily
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Snake SVG
        uses: Platane/snk@v2
        with:
          github_user: sma9lo-ux
          svg: true
          style: retro
          width: 1000
          height: 1000

      - name: Commit and push generated snake SVG
        uses: EndBug/add-and-commit@v9
        with:
          author_name: GitHub Actions
          author_email: actions@github.com
          message: "Generate snake SVG"
